macos_min_version:             # [osx]
  - 10.14                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.14                      # [osx]

# This is done to de-prioritize 1.12
OGRE_VERSION:
  - "1.10"
  - "1.12"
  
ogre:
  {% if OGRE_VERSION == "1.10" %}
  - 1.10
  {% else %}
  - 1.12
  {% endif %}
