macos_min_version:             # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.14                      # [osx and x86_64]

# This is done to de-prioritize 1.12
OGRE_VERSION:
  - "1.10"
  - "1.12"

zip_keys:  # [linux64]
  -  # [linux64]
    - cdt_name  # [linux64]
    - QT_VERSION  # [linux64]

cdt_name:  # [linux64]
  - cos6  # [linux64]
  - cos7  # [linux64]

# This is done to build for both qt (5.12) and qt-main (5.15)
# until conda-forge as an whole migrate to 5.15 
# Disable 5.12 on osx-arm64 (arm64 selector, see
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html)
QT_VERSION:
  - "5.12"  # [not arm64]
  - "5.15"
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
docker_image:                                     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                         # [linux64]
  - cos7                                          # [linux64]
