macos_min_version:             # [osx]
  - 12.0                       # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 12.0                       # [osx]

# This is done to de-prioritize 1.12
OGRE_VERSION:
  - "1.10"
  - "1.12"
  
c_compiler:  # [win]
- vs2019  # [win]
cxx_compiler:  # [win]
- vs2019  # [win]
c_compiler_version:                               # [osx]
  - 11                                            # [osx]
cxx_compiler_version:                             # [osx]
  - 11                                            # [osx]
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
docker_image:                                     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                         # [linux64]
  - cos7                                          # [linux64]
